### ISSUE TITLE
No ClusterIP in prometheus-configmap.yml

### ISSUE THREAD

**Issue by cyrildiagne** [GoogleCloudPlatform/gke-tensorflow-inference-system-tutorial#1]
Hi!

[This part](https://cloud.google.com/solutions/building-a-scalable-tensorflow-inference-system#deploy_monitoring_servers_with_prometheus_and_grafana) of the tutorial refers to
```
sed -i.bak "s/CLUSTER-IP/${TRITON_IP}/" prometheus-configmap.yml
```
But that command has no effect since there is no such pattern in that file.

**Comment by enakai00** [comment]
Thank you for pointing it out. That's right, that line is not necessary (due to a config change in the past). We will remove it from the tutorial document when we'll revise it next time.
